"""
Phase A.0 — cache reload backward-compatibility tests.

Cached pickles created before the cash-flow fields were added must
deserialise successfully under the new dataclass schema, with the new
fields auto-defaulted to empty pd.Series. This is the same pattern used
when ``quarterly_earnings`` / ``quarterly_revenue`` were introduced.

These tests:
  1. Synthesise a *pre-extension* pickle by constructing a dict that
     mirrors the old field set and round-tripping through pickle. This
     simulates the on-disk format of caches created before Phase A.0
     without coupling the test to whatever pickles currently sit in
     ``cache/`` (those may be regenerated by other test runs).
  2. Load every real pickle in the project's ``cache/`` directory and
     assert each one deserialises and exposes the new fields as empty
     Series.  This is the integration check that protects users who
     have months of accumulated cache against a silent breakage.
"""
from __future__ import annotations

import pickle
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data_fetcher import CACHE_SCHEMA_VERSION, StockBundle, _load_from_cache


CACHE_DIR = Path(__file__).resolve().parents[1] / "cache"


def test_synthesised_pre_extension_pickle_loads_with_empty_new_fields(tmp_path):
    """Build a bundle without the new kwargs, pickle it, reload it,
    and confirm all six new fields default to empty Series.

    This is the dataclass-level guarantee: dataclasses with
    ``field(default_factory=...)`` populate missing fields on unpickle
    via __init__ defaults, so adding fields is non-breaking as long as
    the existing ones don't change position or name.
    """
    bundle = StockBundle(
        ticker="OLD.NS", sector="FMCG", name="Old Co",
        price=100.0, market_cap=1e10, shares_outstanding=1e8,
        beta_raw=1.0, price_history=pd.Series(dtype=float),
        eps_ttm=10.0, book_value_per_share=50.0, sales_per_share_ttm=80.0,
        dividend_per_share_ttm=5.0, free_cash_flow_per_share_ttm=8.0,
        revenue=8e9, ebitda=2e9, net_income=1e9,
        total_debt=5e8, cash=1e9, equity=4e9, total_assets=8e9,
        dividends_annual=pd.Series([4.5, 5.0]),
        earnings_annual=pd.Series([9.0, 10.0]),
        revenue_annual=pd.Series([7e9, 8e9]),
        book_value_annual=pd.Series([45.0, 50.0]),
        payout_ratio=0.5, roe=0.20, enterprise_value=1e10,
    )

    path = tmp_path / "OLD.NS.pkl"
    path.write_bytes(pickle.dumps(bundle))

    revived: StockBundle = pickle.loads(path.read_bytes())

    # Old fields intact
    assert revived.ticker == "OLD.NS"
    assert revived.eps_ttm == 10.0
    assert revived.payout_ratio == 0.5

    # New fields auto-defaulted to empty Series
    for name in (
        "net_income_annual", "capex_annual", "dep_amort_annual",
        "change_in_wc_annual", "working_capital_annual", "total_debt_annual",
    ):
        s = getattr(revived, name)
        assert isinstance(s, pd.Series), f"{name} not a Series after reload"
        assert s.empty, f"{name} should be empty for pre-extension pickle"


def _existing_cache_files() -> list[Path]:
    if not CACHE_DIR.exists():
        return []
    return sorted(CACHE_DIR.glob("*.pkl"))


@pytest.mark.skipif(
    not _existing_cache_files(),
    reason="No cached pickles present — nothing to back-compat test against.",
)
def test_all_existing_cache_pickles_deserialise():
    """Every pickle in the project's cache/ directory must load under
    the new schema. This is the integration test that protects users
    with accumulated local cache against a silent breakage on upgrade.
    """
    files = _existing_cache_files()
    assert files, "Expected at least one cache file"

    failures: list[str] = []
    for p in files:
        try:
            b: StockBundle = pickle.loads(p.read_bytes())
        except Exception as exc:
            failures.append(f"{p.name}: {exc.__class__.__name__}: {exc}")
            continue

        # Sanity: required new fields exist as Series
        for name in (
            "net_income_annual", "capex_annual", "dep_amort_annual",
            "change_in_wc_annual", "working_capital_annual", "total_debt_annual",
        ):
            attr = getattr(b, name, None)
            if not isinstance(attr, pd.Series):
                failures.append(
                    f"{p.name}: new field {name!r} is not a Series "
                    f"(got {type(attr).__name__})"
                )

    assert not failures, "Cache reload failures:\n  " + "\n  ".join(failures)


def test_cache_schema_version_is_current_on_fresh_construction():
    """Every freshly-constructed bundle must self-report as the current
    schema version, regardless of which constructor path was taken."""
    bundle = StockBundle(
        ticker="FRESH.NS", sector="FMCG", name="Fresh Co",
        price=100.0, market_cap=1e10, shares_outstanding=1e8,
        beta_raw=1.0, price_history=pd.Series(dtype=float),
        eps_ttm=10.0, book_value_per_share=50.0, sales_per_share_ttm=80.0,
        dividend_per_share_ttm=5.0, free_cash_flow_per_share_ttm=8.0,
        revenue=8e9, ebitda=2e9, net_income=1e9,
        total_debt=5e8, cash=1e9, equity=4e9, total_assets=8e9,
        dividends_annual=pd.Series(dtype=float),
        earnings_annual=pd.Series(dtype=float),
        revenue_annual=pd.Series(dtype=float),
        book_value_annual=pd.Series(dtype=float),
        payout_ratio=0.5, roe=0.20, enterprise_value=1e10,
    )
    assert bundle._schema_version == CACHE_SCHEMA_VERSION


def test_setstate_migrates_pre_version_pickle_to_current_version(tmp_path):
    """A pickle whose __dict__ lacks _schema_version (or has a stale
    value) must be migrated up to CACHE_SCHEMA_VERSION via __setstate__.

    This is the operational guarantee that any code reading
    `bundle._schema_version` after a cache load sees the current
    version, never a stale one.
    """
    # Synthesise a v1-shaped __dict__ by constructing a bundle, then
    # mutating its dict to remove the _schema_version key entirely
    # (mimicking the on-disk shape of pre-Phase-A.0 pickles).
    bundle = StockBundle(
        ticker="V1.NS", sector="FMCG", name="V1 Co",
        price=100.0, market_cap=1e10, shares_outstanding=1e8,
        beta_raw=1.0, price_history=pd.Series(dtype=float),
        eps_ttm=10.0, book_value_per_share=50.0, sales_per_share_ttm=80.0,
        dividend_per_share_ttm=5.0, free_cash_flow_per_share_ttm=8.0,
        revenue=8e9, ebitda=2e9, net_income=1e9,
        total_debt=5e8, cash=1e9, equity=4e9, total_assets=8e9,
        dividends_annual=pd.Series(dtype=float),
        earnings_annual=pd.Series(dtype=float),
        revenue_annual=pd.Series(dtype=float),
        book_value_annual=pd.Series(dtype=float),
        payout_ratio=0.5, roe=0.20, enterprise_value=1e10,
    )
    state = bundle.__dict__.copy()
    # Drop the new field set + the schema version key — this is the
    # on-disk shape of a v1 pickle.
    for k in (
        "_schema_version",
        "net_income_annual", "capex_annual", "dep_amort_annual",
        "change_in_wc_annual", "working_capital_annual", "total_debt_annual",
    ):
        state.pop(k, None)
    raw_state = pickle.dumps((StockBundle, state))

    # Manually reconstruct via __setstate__ (the same path pickle.loads
    # exercises for a v1-shaped state dict).
    klass, restored_state = pickle.loads(raw_state)
    revived = klass.__new__(klass)
    revived.__setstate__(restored_state)

    assert revived._schema_version == CACHE_SCHEMA_VERSION
    # And every backfilled field is now a Series (not missing).
    for name in (
        "net_income_annual", "capex_annual", "dep_amort_annual",
        "change_in_wc_annual", "working_capital_annual", "total_debt_annual",
    ):
        assert isinstance(getattr(revived, name), pd.Series)
        assert getattr(revived, name).empty


@pytest.mark.skipif(
    not _existing_cache_files(),
    reason="No cached pickles present.",
)
def test_load_from_cache_helper_handles_pre_extension_pickles():
    """`_load_from_cache` is the public entry point for cache reads.
    It must succeed and return a StockBundle with the new fields, even
    when the on-disk pickle predates the field additions.
    """
    files = _existing_cache_files()
    sample = files[0]
    ticker = sample.stem  # e.g. "TCS.NS.pkl" → "TCS.NS"

    bundle = _load_from_cache(ticker, ttl=None)  # any-age, ignore TTL
    assert bundle is not None, f"Expected to load {ticker} from {sample}"
    # The six new fields must be present and well-typed.
    for name in (
        "net_income_annual", "capex_annual", "dep_amort_annual",
        "change_in_wc_annual", "working_capital_annual", "total_debt_annual",
    ):
        assert isinstance(getattr(bundle, name), pd.Series)
